# Use https://travis-ci.org/ for automatic testing
language: go

go:
# Use only the latest version
  - 1.4
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - make deps
script:
  - make build
after_success:
  - make release